import type {
  Agreement,
  ChatMessage,
  MarketPrice,
  NegotiationIteration,
  Notification,
  Offer,
  OfferResponse,
  OperatorContacts,
  Organization,
  RegistrationApplication,
  User,
} from "./types";

export const OPERATOR_CONTACTS: OperatorContacts = {
  organization_name: "ПАО «ГарантПоставщик»",
  phone: "+7 (495) 123-45-67",
  email: "gp@energymarket-pilot.ru",
  address: "г. Москва, ул. Энергетическая, д. 1",
};

export const organizations: Organization[] = [
  {
    id: "org_garant",
    name: "ПАО «ГарантПоставщик»",
    inn: "7701234567",
    ogrn: "1027700132195",
    type: "operator",
    region: "moscow_region",
    status: "active",
    created_at: "2026-02-01T08:00:00Z",
    verified_at: "2026-02-01T09:00:00Z",
    completed_agreements_count: 12,
    contact_email: "gp@energymarket-pilot.ru",
    contact_phone: "+7 (495) 123-45-67",
    contact_full_name: "Иванов Сергей Петрович",
  },
  {
    id: "org_mosenergo",
    name: "ПАО «МосЭнерго»",
    inn: "7708004767",
    ogrn: "1027700042191",
    type: "producer_wholesale",
    region: "moscow_region",
    generation_type: "tes_gas",
    installed_capacity: 1200,
    orem_contract_number: "ОРЭМ-2024-00891",
    status: "active",
    created_at: "2026-02-05T10:00:00Z",
    verified_at: "2026-02-06T11:00:00Z",
    completed_agreements_count: 5,
    contact_email: "trade@mosenergo.ru",
    contact_phone: "+7 (495) 987-65-43",
    contact_full_name: "Петров Алексей Николаевич",
  },
  {
    id: "org_energoset",
    name: "ООО «ЭнергоСеть»",
    inn: "6312345678",
    ogrn: "1166312345678",
    type: "energy_sales",
    region: "samara",
    status: "active",
    created_at: "2026-02-10T09:00:00Z",
    verified_at: "2026-02-11T10:00:00Z",
    completed_agreements_count: 3,
    contact_email: "sales@energoset63.ru",
    contact_phone: "+7 (846) 200-30-40",
    contact_full_name: "Сидорова Мария Ивановна",
  },
  {
    id: "org_zavod",
    name: "АО «Завод Приборов»",
    inn: "6658123456",
    ogrn: "1026601234567",
    type: "consumer",
    region: "sverdlovsk",
    price_category: "4",
    max_power: 45,
    status: "active",
    created_at: "2026-02-08T08:00:00Z",
    verified_at: "2026-02-09T12:00:00Z",
    completed_agreements_count: 2,
    contact_email: "energy@zavod-priborov.ru",
    contact_phone: "+7 (343) 111-22-33",
    contact_full_name: "Козлов Дмитрий Андреевич",
  },
  {
    id: "org_vetro",
    name: "ООО «ВетроЭнерго»",
    inn: "2308123456",
    ogrn: "1152308123456",
    type: "producer_retail",
    region: "krasnoyarsk",
    generation_type: "vie_wind",
    installed_capacity: 85,
    status: "active",
    created_at: "2026-02-12T07:00:00Z",
    verified_at: "2026-02-13T08:00:00Z",
    completed_agreements_count: 1,
    contact_email: "info@vetroenergo.ru",
    contact_phone: "+7 (391) 555-66-77",
    contact_full_name: "Новикова Елена Сергеевна",
  },
  {
    id: "org_aggregat",
    name: "ООО «АгрегатЭнерго»",
    inn: "5260123456",
    ogrn: "1175260123456",
    type: "demand_aggregator",
    region: "nizhny_novgorod",
    status: "active",
    created_at: "2026-02-14T10:00:00Z",
    verified_at: "2026-02-15T11:00:00Z",
    completed_agreements_count: 0,
    contact_email: "dr@aggregatenergo.ru",
    contact_phone: "+7 (831) 400-50-60",
    contact_full_name: "Волков Игорь Павлович",
  },
  {
    id: "org_energoservice",
    name: "ЗАО «ЭнергоСервис»",
    inn: "5406123456",
    ogrn: "1025406123456",
    type: "service_provider",
    region: "novosibirsk",
    status: "active",
    created_at: "2026-02-16T09:00:00Z",
    verified_at: "2026-02-17T10:00:00Z",
    completed_agreements_count: 4,
    contact_email: "service@energoservice54.ru",
    contact_phone: "+7 (383) 300-40-50",
    contact_full_name: "Морозова Анна Викторовна",
  },
];

export const users: User[] = [
  {
    id: "user_operator",
    organization_id: "org_garant",
    email: "operator@gp.ru",
    full_name: "Иванов Сергей Петрович",
    phone: "+7 (495) 123-45-67",
    role: "operator",
    status: "active",
    created_at: "2026-02-01T08:00:00Z",
  },
  {
    id: "user_mosenergo",
    organization_id: "org_mosenergo",
    email: "trade@mosenergo.ru",
    full_name: "Петров Алексей Николаевич",
    phone: "+7 (495) 987-65-43",
    role: "producer_wholesale",
    status: "active",
    created_at: "2026-02-06T11:00:00Z",
  },
  {
    id: "user_energoset",
    organization_id: "org_energoset",
    email: "sales@energoset63.ru",
    full_name: "Сидорова Мария Ивановна",
    phone: "+7 (846) 200-30-40",
    role: "energy_sales",
    status: "active",
    created_at: "2026-02-11T10:00:00Z",
  },
  {
    id: "user_zavod_priborov",
    organization_id: "org_zavod",
    email: "energy@zavod-priborov.ru",
    full_name: "Козлов Дмитрий Андреевич",
    phone: "+7 (343) 111-22-33",
    role: "consumer",
    status: "active",
    created_at: "2026-02-09T12:00:00Z",
  },
  {
    id: "user_vetro",
    organization_id: "org_vetro",
    email: "info@vetroenergo.ru",
    full_name: "Новикова Елена Сергеевна",
    phone: "+7 (391) 555-66-77",
    role: "producer_retail",
    status: "active",
    created_at: "2026-02-13T08:00:00Z",
  },
  {
    id: "user_aggregat",
    organization_id: "org_aggregat",
    email: "dr@aggregatenergo.ru",
    full_name: "Волков Игорь Павлович",
    phone: "+7 (831) 400-50-60",
    role: "demand_aggregator",
    status: "active",
    created_at: "2026-02-15T11:00:00Z",
  },
  {
    id: "user_energoservice",
    organization_id: "org_energoservice",
    email: "service@energoservice54.ru",
    full_name: "Морозова Анна Викторовна",
    phone: "+7 (383) 300-40-50",
    role: "service_provider",
    status: "active",
    created_at: "2026-02-17T10:00:00Z",
  },
];

export const offers: Offer[] = [
  {
    id: "offer_ee_sell_fixed",
    author_id: "user_mosenergo",
    organization_id: "org_mosenergo",
    commodity_category: "energy",
    direction: "sell",
    status: "in_negotiation",
    generation_type: "tes_gas",
    generation_object: "ТЭЦ-21",
    region: ["moscow_region"],
    price: 1850,
    price_type: "fixed",
    volume_min: 50,
    volume_max: 150,
    period_start: "2026-07-01",
    period_end: "2026-12-31",
    delivery_profile: "base",
    has_green_attrs: false,
    description: "Поставка по свободному договору в рамках пилота.",
    valid_until: "2026-06-15",
    published_at: "2026-03-01T10:00:00Z",
    created_at: "2026-02-28T09:00:00Z",
    response_count: 2,
  },
  {
    id: "offer_ee_sell_indexed",
    author_id: "user_vetro",
    organization_id: "org_vetro",
    commodity_category: "energy",
    direction: "sell",
    status: "active",
    generation_type: "vie_wind",
    generation_object: "ВЭС «Северный ветер»",
    region: ["krasnoyarsk"],
    price: 2100,
    price_type: "indexed",
    volume_min: 10,
    volume_max: 40,
    period_start: "2026-08-01",
    period_end: "2027-06-30",
    delivery_profile: "custom",
    has_green_attrs: true,
    valid_until: "2026-07-01",
    published_at: "2026-03-05T11:00:00Z",
    created_at: "2026-03-04T08:00:00Z",
    response_count: 0,
  },
  {
    id: "offer_ee_sell_zonal",
    author_id: "user_energoset",
    organization_id: "org_energoset",
    commodity_category: "energy",
    direction: "sell",
    status: "active",
    generation_type: "other",
    generation_object: "Портфель поставок",
    region: ["samara", "nizhny_novgorod"],
    price_type: "zonal",
    price_peak: 2200,
    price_semipeak: 1950,
    price_offpeak: 1600,
    price: 1950,
    volume_min: 20,
    volume_max: 80,
    period_start: "2026-09-01",
    period_end: "2026-12-31",
    delivery_profile: "peak",
    has_green_attrs: false,
    valid_until: "2026-08-20",
    published_at: "2026-03-08T09:00:00Z",
    created_at: "2026-03-07T10:00:00Z",
    response_count: 1,
  },
  {
    id: "offer_ee_buy",
    author_id: "user_zavod_priborov",
    organization_id: "org_zavod",
    commodity_category: "energy",
    direction: "buy",
    status: "active",
    region: ["sverdlovsk"],
    price: 1750,
    price_type: "fixed",
    volume_min: 30,
    volume_max: 60,
    period_start: "2026-07-01",
    period_end: "2026-12-31",
    delivery_profile: "base",
    has_green_attrs: false,
    valid_until: "2026-06-30",
    published_at: "2026-03-02T14:00:00Z",
    created_at: "2026-03-01T12:00:00Z",
    response_count: 0,
  },
  {
    id: "offer_ee_buy_2",
    author_id: "user_zavod_priborov",
    organization_id: "org_zavod",
    commodity_category: "energy",
    direction: "buy",
    status: "draft",
    region: ["sverdlovsk"],
    price: 1700,
    price_type: "fixed",
    volume_min: 15,
    volume_max: 25,
    period_start: "2027-01-01",
    period_end: "2027-06-30",
    delivery_profile: "offpeak",
    has_green_attrs: false,
    valid_until: "2026-12-01",
    created_at: "2026-03-10T08:00:00Z",
  },
  {
    id: "offer_cap_sell",
    author_id: "user_mosenergo",
    organization_id: "org_mosenergo",
    commodity_category: "capacity",
    direction: "sell",
    status: "in_negotiation",
    generation_type: "tes_gas",
    generation_object: "ТЭЦ-21",
    region: ["moscow_region"],
    capacity_volume: 80,
    capacity_price: 245000,
    capacity_price_type: "fixed",
    installed_capacity: 200,
    min_contract_months: 12,
    period_start: "2026-07-01",
    period_end: "2027-06-30",
    has_green_attrs: false,
    valid_until: "2026-06-01",
    published_at: "2026-02-20T10:00:00Z",
    created_at: "2026-02-19T09:00:00Z",
    response_count: 1,
  },
  {
    id: "offer_cap_sell_2",
    author_id: "user_vetro",
    organization_id: "org_vetro",
    commodity_category: "capacity",
    direction: "sell",
    status: "active",
    generation_type: "vie_wind",
    generation_object: "ВЭС «Северный ветер»",
    region: ["krasnoyarsk"],
    capacity_volume: 25,
    capacity_price: 198000,
    capacity_price_type: "indexed",
    installed_capacity: 85,
    min_contract_months: 6,
    period_start: "2026-08-01",
    period_end: "2027-01-31",
    has_green_attrs: true,
    valid_until: "2026-07-15",
    published_at: "2026-03-06T12:00:00Z",
    created_at: "2026-03-05T11:00:00Z",
    response_count: 0,
  },
  {
    id: "offer_cap_buy",
    author_id: "user_zavod_priborov",
    organization_id: "org_zavod",
    commodity_category: "capacity",
    direction: "buy",
    status: "active",
    region: ["sverdlovsk"],
    capacity_volume: 40,
    capacity_price: 230000,
    capacity_price_type: "fixed",
    min_contract_months: 12,
    period_start: "2026-07-01",
    period_end: "2027-06-30",
    has_green_attrs: false,
    valid_until: "2026-06-20",
    published_at: "2026-03-03T10:00:00Z",
    created_at: "2026-03-02T09:00:00Z",
    response_count: 0,
  },
  {
    id: "offer_svc_sell",
    author_id: "user_energoservice",
    organization_id: "org_energoservice",
    commodity_category: "service",
    direction: "sell",
    status: "agreed",
    region: ["novosibirsk"],
    service_category: "energy_audit",
    service_description:
      "Комплексный энергоаудит промышленного предприятия с отчётом и рекомендациями.",
    service_price_text: "от 450 000 ₽ за объект",
    service_price_numeric: 450000,
    service_unit: "за объект",
    has_green_attrs: false,
    valid_until: "2026-09-30",
    published_at: "2026-02-25T09:00:00Z",
    created_at: "2026-02-24T08:00:00Z",
    response_count: 1,
  },
  {
    id: "offer_svc_buy_dr",
    author_id: "user_zavod_priborov",
    organization_id: "org_zavod",
    commodity_category: "service",
    direction: "buy",
    status: "active",
    region: ["sverdlovsk"],
    service_category: "demand_response",
    service_description: "Услуги управления спросом на пиковые часы.",
    service_price_text: "по договорённости",
    has_green_attrs: false,
    valid_until: "2026-08-01",
    published_at: "2026-03-09T10:00:00Z",
    created_at: "2026-03-08T09:00:00Z",
    response_count: 0,
  },
  {
    id: "offer_svc_sell_dr",
    author_id: "user_aggregat",
    organization_id: "org_aggregat",
    commodity_category: "service",
    direction: "sell",
    status: "active",
    region: ["nizhny_novgorod"],
    service_category: "demand_response",
    service_description: "Агрегированное снижение нагрузки до 15 МВт.",
    service_price_text: "1 200 ₽/МВт·ч снижения",
    service_price_numeric: 1200,
    service_unit: "₽/МВт·ч",
    has_green_attrs: false,
    valid_until: "2026-10-01",
    published_at: "2026-03-07T08:00:00Z",
    created_at: "2026-03-06T07:00:00Z",
    response_count: 0,
  },
  {
    id: "offer_ee_agreed",
    author_id: "user_energoset",
    organization_id: "org_energoset",
    commodity_category: "energy",
    direction: "sell",
    status: "agreed",
    generation_type: "tes_gas",
    generation_object: "Блок №2",
    region: ["samara"],
    price: 1920,
    price_type: "fixed",
    volume_min: 25,
    volume_max: 25,
    period_start: "2026-04-01",
    period_end: "2026-09-30",
    delivery_profile: "base",
    has_green_attrs: false,
    valid_until: "2026-03-01",
    published_at: "2026-01-15T10:00:00Z",
    created_at: "2026-01-14T09:00:00Z",
    response_count: 1,
  },
];

export const offerResponses: OfferResponse[] = [
  {
    id: "resp_ee_1",
    offer_id: "offer_ee_sell_fixed",
    respondent_id: "user_zavod_priborov",
    respondent_organization_id: "org_zavod",
    status: "counter_received",
    created_at: "2026-03-02T15:00:00Z",
    last_action_at: "2026-03-04T11:00:00Z",
    last_action_type: "counter",
  },
  {
    id: "resp_cap_1",
    offer_id: "offer_cap_sell",
    respondent_id: "user_zavod_priborov",
    respondent_organization_id: "org_zavod",
    status: "counter_received",
    created_at: "2026-02-25T12:00:00Z",
    last_action_at: "2026-03-01T09:00:00Z",
    last_action_type: "counter",
  },
  {
    id: "resp_svc_agreed",
    offer_id: "offer_svc_sell",
    respondent_id: "user_zavod_priborov",
    respondent_organization_id: "org_zavod",
    status: "agreed",
    created_at: "2026-02-26T10:00:00Z",
    last_action_at: "2026-02-28T16:00:00Z",
    last_action_type: "accept",
  },
];

export const negotiationIterations: NegotiationIteration[] = [
  {
    id: "iter_ee_1",
    response_id: "resp_ee_1",
    author_id: "user_zavod_priborov",
    action: "response",
    price: 1850,
    volume_energy: 100,
    period_start: "2026-07-01",
    period_end: "2026-12-31",
    comment: "Готовы принять объём 100 МВт·ч/час.",
    created_at: "2026-03-02T15:00:00Z",
  },
  {
    id: "iter_ee_2",
    response_id: "resp_ee_1",
    author_id: "user_mosenergo",
    action: "counter",
    price: 1880,
    volume_energy: 90,
    period_start: "2026-07-01",
    period_end: "2026-12-31",
    comment: "Контрпредложение: цена 1 880 ₽/МВт·ч, объём 90.",
    created_at: "2026-03-04T11:00:00Z",
  },
  {
    id: "iter_cap_1",
    response_id: "resp_cap_1",
    author_id: "user_zavod_priborov",
    action: "response",
    price_capacity: 245000,
    volume_capacity: 40,
    period_start: "2026-07-01",
    period_end: "2027-06-30",
    created_at: "2026-02-25T12:00:00Z",
  },
  {
    id: "iter_cap_2",
    response_id: "resp_cap_1",
    author_id: "user_mosenergo",
    action: "counter",
    price_capacity: 250000,
    volume_capacity: 40,
    period_start: "2026-07-01",
    period_end: "2027-06-30",
    comment: "Минимальная цена с учётом индексации.",
    created_at: "2026-02-28T14:00:00Z",
  },
  {
    id: "iter_cap_3",
    response_id: "resp_cap_1",
    author_id: "user_zavod_priborov",
    action: "counter",
    price_capacity: 247000,
    volume_capacity: 40,
    period_start: "2026-07-01",
    period_end: "2027-06-30",
    created_at: "2026-03-01T09:00:00Z",
  },
  {
    id: "iter_svc_1",
    response_id: "resp_svc_agreed",
    author_id: "user_zavod_priborov",
    action: "response",
    service_price_text: "450 000 ₽",
    service_terms: "Аудит в течение 30 рабочих дней.",
    created_at: "2026-02-26T10:00:00Z",
  },
  {
    id: "iter_svc_2",
    response_id: "resp_svc_agreed",
    author_id: "user_energoservice",
    action: "accept",
    service_price_text: "450 000 ₽",
    service_terms: "Аудит в течение 30 рабочих дней.",
    created_at: "2026-02-28T16:00:00Z",
  },
];

export const chatMessages: ChatMessage[] = [
  {
    id: "chat_1",
    response_id: "resp_ee_1",
    author_id: "user_zavod_priborov",
    text: "Уточните, пожалуйста, возможность поставки в выходные дни.",
    is_read: true,
    created_at: "2026-03-03T10:00:00Z",
  },
  {
    id: "chat_2",
    response_id: "resp_ee_1",
    author_id: "user_mosenergo",
    text: "Поставка по базовому профилю включает все дни недели.",
    is_read: false,
    created_at: "2026-03-03T14:30:00Z",
  },
];

export const agreements: Agreement[] = [
  {
    id: "agr_svc_1",
    response_id: "resp_svc_agreed",
    seller_id: "org_energoservice",
    buyer_id: "org_zavod",
    commodity_category: "service",
    service_category: "energy_audit",
    final_service_price: "450 000 ₽",
    final_service_terms: "Аудит в течение 30 рабочих дней.",
    final_service_price_numeric: 450000,
    status: "agreed",
    agreed_at: "2026-02-28T16:00:00Z",
    created_at: "2026-02-28T16:00:00Z",
    iteration_count: 2,
    negotiation_days: 2,
  },
];

const months = [
  "2025-10",
  "2025-11",
  "2025-12",
  "2026-01",
  "2026-02",
  "2026-03",
];

function buildRsvPrices(): MarketPrice[] {
  const base: Record<string, number> = {
    moscow_region: 1820,
    nizhny_novgorod: 1750,
    samara: 1780,
    sverdlovsk: 1810,
    krasnoyarsk: 1690,
    novosibirsk: 1720,
    primorsky: 1900,
  };
  const result: MarketPrice[] = [];
  let i = 0;
  for (const region of Object.keys(base) as import("./types").PilotRegion[]) {
    months.forEach((period, mi) => {
      result.push({
        id: `rsv_${region}_${period}`,
        price_type: "rsv",
        region,
        period,
        price: base[region]! + mi * 15 + (i % 3) * 5,
        source: "Ручная загрузка оператором",
        uploaded_by: "user_operator",
        uploaded_at: "2026-03-01T08:00:00Z",
      });
    });
    i++;
  }
  return result;
}

export const marketPrices: MarketPrice[] = [
  ...buildRsvPrices(),
  ...(
    [
      "moscow_region",
      "samara",
      "sverdlovsk",
    ] as import("./types").PilotRegion[]
  ).map((region, idx) => ({
    id: `cap_${region}_2026-02`,
    price_type: "capacity" as const,
    region,
    period: "2026-02",
    price: 235000 + idx * 8000,
    source: "Справочные данные пилота",
    uploaded_by: "user_operator",
    uploaded_at: "2026-03-01T08:00:00Z",
  })),
];

export const notifications: Notification[] = [
  {
    id: "not_1",
    user_id: "user_mosenergo",
    type: "N04",
    title: "Новый отклик на предложение",
    body: "АО «Завод Приборов» откликнулось на продажу ЭЭ (ТЭЦ-21).",
    related_entity_type: "offer_response",
    related_entity_id: "resp_ee_1",
    is_read: false,
    channel: "system_email",
    sent_at: "2026-03-02T15:05:00Z",
    category_filter: "negotiations",
  },
  {
    id: "not_2",
    user_id: "user_zavod_priborov",
    type: "N05",
    title: "Контрпредложение получено",
    body: "ПАО «МосЭнерго» направило контрпредложение по переговорам № resp_ee_1.",
    related_entity_type: "offer_response",
    related_entity_id: "resp_ee_1",
    is_read: false,
    channel: "system_email",
    sent_at: "2026-03-04T11:05:00Z",
    category_filter: "negotiations",
  },
  {
    id: "not_3",
    user_id: "user_zavod_priborov",
    type: "N07",
    title: "Принципиальное согласие достигнуто",
    body: "Согласие по услуге энергоаудита с ЗАО «ЭнергоСервис».",
    related_entity_type: "agreement",
    related_entity_id: "agr_svc_1",
    is_read: true,
    channel: "system_email",
    sent_at: "2026-02-28T16:05:00Z",
    category_filter: "negotiations",
  },
  {
    id: "not_4",
    user_id: "user_mosenergo",
    type: "N06",
    title: "Контрпредложение от инициатора",
    body: "АО «Завод Приборов» направило встречное контрпредложение по мощности.",
    related_entity_type: "offer_response",
    related_entity_id: "resp_cap_1",
    is_read: true,
    channel: "system",
    sent_at: "2026-03-01T09:05:00Z",
    category_filter: "negotiations",
  },
  {
    id: "not_5",
    user_id: "user_zavod_priborov",
    type: "N10",
    title: "Срок действия предложения истекает",
    body: "Через 3 дня истекает срок предложения о покупке ЭЭ.",
    related_entity_type: "offer",
    related_entity_id: "offer_ee_buy",
    is_read: false,
    channel: "system",
    sent_at: "2026-03-07T08:00:00Z",
    category_filter: "offers",
  },
  {
    id: "not_6",
    user_id: "user_operator",
    type: "N01",
    title: "Новая заявка на присоединение",
    body: "Поступила заявка от ООО «ПромЭнерго».",
    related_entity_type: "registration",
    related_entity_id: "app_pending_1",
    is_read: false,
    channel: "system_email",
    sent_at: "2026-03-09T09:00:00Z",
    category_filter: "system",
  },
  {
    id: "not_7",
    user_id: "user_zavod_priborov",
    type: "N11",
    title: "Новое сообщение в чате",
    body: "ПАО «МосЭнерго» ответило в чате переговоров.",
    related_entity_type: "offer_response",
    related_entity_id: "resp_ee_1",
    is_read: false,
    channel: "system",
    sent_at: "2026-03-03T14:35:00Z",
    category_filter: "negotiations",
  },
  {
    id: "not_8",
    user_id: "user_mosenergo",
    type: "N12",
    title: "Ожидание ответа более 3 дней",
    body: "Напоминание: ожидается ваш ответ по переговорам по мощности.",
    related_entity_type: "offer_response",
    related_entity_id: "resp_cap_1",
    is_read: false,
    channel: "system_email",
    sent_at: "2026-03-05T10:00:00Z",
    category_filter: "negotiations",
  },
  {
    id: "not_9",
    user_id: "user_energoset",
    type: "N04",
    title: "Новый отклик на предложение",
    body: "Новый отклик на зональное предложение (портфель).",
    related_entity_type: "offer",
    related_entity_id: "offer_ee_sell_zonal",
    is_read: true,
    channel: "system",
    sent_at: "2026-03-08T12:00:00Z",
    category_filter: "offers",
  },
  {
    id: "not_10",
    user_id: "user_zavod_priborov",
    type: "N03",
    title: "Новое предложение по профилю",
    body: "Опубликовано предложение о продаже ЭЭ (ВИЭ) в вашем регионе.",
    related_entity_type: "offer",
    related_entity_id: "offer_ee_sell_indexed",
    is_read: true,
    channel: "system",
    sent_at: "2026-03-05T11:10:00Z",
    category_filter: "offers",
  },
];

export const registrationApplications: RegistrationApplication[] = [
  {
    id: "app_pending_1",
    application_number: "ЗАЯВ-2026-0042",
    role: "consumer",
    organization_name: "ООО «ПромЭнерго»",
    inn: "5401987654",
    ogrn: "1155401987654",
    region: "novosibirsk",
    contact_full_name: "Лебедев Павел Олегович",
    email: "join@promenergo.ru",
    phone: "+7 (383) 222-33-44",
    price_category: "5",
    max_power: 12,
    status: "pending_review",
    created_at: "2026-03-09T08:30:00Z",
  },
  {
    id: "app_info_1",
    application_number: "ЗАЯВ-2026-0038",
    role: "producer_retail",
    organization_name: "ООО «Солнце+»",
    inn: "2508123999",
    ogrn: "1182508123999",
    region: "primorsky",
    contact_full_name: "Орлова Ксения Дмитриевна",
    email: "info@solnce-plus.ru",
    phone: "+7 (423) 300-11-22",
    generation_type: "vie_solar",
    installed_capacity: 5,
    status: "info_requested",
    operator_comment: "Приложите копию договора о подключении к сетям.",
    created_at: "2026-03-05T14:00:00Z",
  },
];

export let currentUserId = "user_zavod_priborov";

export function switchUser(id: string): void {
  currentUserId = id;
}

export function getDemoUsers(): User[] {
  return users.filter((u) => u.role !== "admin");
}

export function getPublicStats() {
  const activeOffers = offers.filter(
    (o) => o.status === "active" || o.status === "in_negotiation",
  ).length;
  const participants = organizations.filter(
    (o) => o.status === "active" && o.type !== "operator",
  ).length;
  return {
    participants,
    activeOffers,
    agreements: agreements.length,
  };
}
